export const myProjects = [
  {
    title: "Front-side",
    projectName: "Travel easily",
    githubLink: "https://github.com/DavidErenfeld/travel-Easily-App-Front.git",
    websiteLink: "https://travel-easily-app.netlify.app",
    technologies: [
      "React",
      "TypeScript",
      "Socket.IO",
      "React i18next",
      "Google OAuth",
      "CSS",
    ],
  },
  {
    title: "Server-side",
    projectName: "Travel easily",
    githubLink: "https://github.com/DavidErenfeld/TravelEasilyAppBackend.git",
    websiteLink:
      "https://evening-bayou-77034-176dc93fb1e1.herokuapp.com/api-docs/",
    technologies: [
      "NodeJS",
      "TypeScript",
      "JWT",
      "Google OAuth",
      "Google API",
      "PostgreSQL",
      "Redis",
      "Jest",
      "Swagger",
    ],
  },
  {
    title: "Front-side",
    projectName: "Starbuks Locations",
    githubLink: "https://github.com/DavidErenfeld/Task_Locations.git",
    websiteLink: "https://task-locations-david-erenfeld.netlify.app/",
    technologies: ["React", "JavaScript", "CSS", "OpenLayers"],
  },
  {
    title: "Server-side",
    projectName: "Starbuks Locations",
    githubLink: "https://github.com/DavidErenfeld/Geo-Location-Service.git",
    websiteLink: "https://geo-location-service-b0911ef2477e.herokuapp.com/",
    technologies: ["NodeJS", "JavaScript", "Express", "Turf.js", "Docker"],
  },
  {
    title: "Front-side",
    projectName: "Code Mentor",
    githubLink: "https://github.com/DavidErenfeld/Code_Mentor_Front.git",
    websiteLink: "https://codementor-daviderenfeld.netlify.app/",
    technologies: ["React", "JavaScript", "CSS", "Socket.IO"],
  },
  {
    title: "Server-side",
    projectName: "Code Mentor",
    githubLink: "https://github.com/DavidErenfeld/Code_Mentor_Server.git",
    websiteLink:
      "https://boiling-springs-91338-006b899baec7.herokuapp.com/codeBlocks",
    technologies: ["NodeJS", "JavaScript", "Express", "MongoDB", "Socket.IO"],
  },
  {
    title: "Front-side",
    projectName: "My Portfolio",
    githubLink: "https://github.com/DavidErenfeld/myPortfolio.git",
    websiteLink: "https://david-erenfeld.netlify.app/",
    technologies: ["React", "JavaScript", "CSS"],
  },
  {
    title: "vanilla js",
    projectName: "Pig game",
    githubLink: "https://github.com/DavidErenfeld/Pig-Game.git",
    websiteLink: "https://tranquil-syrniki-b95ab5.netlify.app/",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
];
